import os

DEFAULT_FAKE_VALUE = 'fake one'

class Env:
    NOTION_TOKEN_V2 = os.getenv('NOTION_TOKEN_V2', DEFAULT_FAKE_VALUE)
    NOTION_WORKSPACE_ID = os.getenv('NOTION_WORKSPACE_ID', DEFAULT_FAKE_VALUE)
    NOTION_TABLE_ID = os.getenv('NOTION_TABLE_ID', DEFAULT_FAKE_VALUE)

    OPENAI_API_KEY = os.getenv('OPENAI_API_KEY', DEFAULT_FAKE_VALUE)