import { DrawingBearer } from './communication-objects/DrawingObject.fabric';

export const drawingJSON: DrawingBearer = {
    "version": "2.4.6",
    "objects": [
        {
            "type": "path",
            "version": "2.4.6",
            "originX": "left",
            "originY": "top",
            "left": 443.49699999999996,
            "top": 178.5,
            "width": 423.00600000000003,
            "height": 10,
            "fill": null,
            "stroke": "black",
            "strokeWidth": 3,
            "strokeDashArray": null,
            "strokeLineCap": "round",
            "strokeDashOffset": 0,
            "strokeLineJoin": "round",
            "strokeMiterLimit": 10,
            "scaleX": 1,
            "scaleY": 1,
            "angle": 0,
            "flipX": false,
            "flipY": false,
            "opacity": 1,
            "shadow": null,
            "visible": true,
            "clipTo": null,
            "backgroundColor": "",
            "fillRule": "nonzero",
            "paintFirst": "fill",
            "globalCompositeOperation": "source-over",
            "transformMatrix": null,
            "skewX": 0,
            "skewY": 0,
            "path": [
                [
                    "M",
                    444.997,
                    180
                ],
                [
                    "Q",
                    445,
                    180,
                    447.5,
                    180
                ],
                [
                    "Q",
                    450,
                    180,
                    456.5,
                    180
                ],
                [
                    "Q",
                    463,
                    180,
                    490.5,
                    180
                ],
                [
                    "Q",
                    518,
                    180,
                    540.5,
                    181
                ],
                [
                    "Q",
                    563,
                    182,
                    591.5,
                    182
                ],
                [
                    "Q",
                    620,
                    182,
                    650.5,
                    183.5
                ],
                [
                    "Q",
                    681,
                    185,
                    712.5,
                    186
                ],
                [
                    "Q",
                    744,
                    187,
                    770,
                    187.5
                ],
                [
                    "Q",
                    796,
                    188,
                    813,
                    188.5
                ],
                [
                    "Q",
                    830,
                    189,
                    841.5,
                    189
                ],
                [
                    "Q",
                    853,
                    189,
                    859.5,
                    189.5
                ],
                [
                    "Q",
                    866,
                    190,
                    866.5,
                    190
                ],
                [
                    "Q",
                    867,
                    190,
                    867.5,
                    190
                ],
                [
                    "L",
                    868.003,
                    190
                ]
            ]
        },
        {
            "type": "path",
            "version": "2.4.6",
            "originX": "left",
            "originY": "top",
            "left": 433.49699999999996,
            "top": 266.5,
            "width": 480.00600000000003,
            "height": 14,
            "fill": null,
            "stroke": "black",
            "strokeWidth": 3,
            "strokeDashArray": [
                2,
                10
            ],
            "strokeLineCap": "round",
            "strokeDashOffset": 0,
            "strokeLineJoin": "round",
            "strokeMiterLimit": 10,
            "scaleX": 1,
            "scaleY": 1,
            "angle": 0,
            "flipX": false,
            "flipY": false,
            "opacity": 1,
            "shadow": null,
            "visible": true,
            "clipTo": null,
            "backgroundColor": "",
            "fillRule": "nonzero",
            "paintFirst": "fill",
            "globalCompositeOperation": "source-over",
            "transformMatrix": null,
            "skewX": 0,
            "skewY": 0,
            "path": [
                [
                    "M",
                    434.997,
                    268
                ],
                [
                    "Q",
                    435,
                    268,
                    436,
                    268
                ],
                [
                    "Q",
                    437,
                    268,
                    440.5,
                    268.5
                ],
                [
                    "Q",
                    444,
                    269,
                    451.5,
                    270.5
                ],
                [
                    "Q",
                    459,
                    272,
                    468,
                    273.5
                ],
                [
                    "Q",
                    477,
                    275,
                    488,
                    276
                ],
                [
                    "Q",
                    499,
                    277,
                    517,
                    277.5
                ],
                [
                    "Q",
                    535,
                    278,
                    553,
                    278
                ],
                [
                    "Q",
                    571,
                    278,
                    604,
                    278
                ],
                [
                    "Q",
                    637,
                    278,
                    661.5,
                    279
                ],
                [
                    "Q",
                    686,
                    280,
                    710.5,
                    280
                ],
                [
                    "Q",
                    735,
                    280,
                    761.5,
                    280.5
                ],
                [
                    "Q",
                    788,
                    281,
                    811.5,
                    281.5
                ],
                [
                    "Q",
                    835,
                    282,
                    852,
                    282
                ],
                [
                    "Q",
                    869,
                    282,
                    880,
                    282
                ],
                [
                    "Q",
                    891,
                    282,
                    897,
                    282
                ],
                [
                    "Q",
                    903,
                    282,
                    907.5,
                    282
                ],
                [
                    "Q",
                    912,
                    282,
                    913,
                    282
                ],
                [
                    "Q",
                    914,
                    282,
                    914.5,
                    282
                ],
                [
                    "L",
                    915.003,
                    282
                ]
            ]
        },
        {
            "type": "circle",
            "version": "2.4.6",
            "originX": "left",
            "originY": "top",
            "left": 518,
            "top": 324,
            "width": 204,
            "height": 204,
            "fill": "transparent",
            "stroke": "black",
            "strokeWidth": 3,
            "strokeDashArray": null,
            "strokeLineCap": "butt",
            "strokeDashOffset": 0,
            "strokeLineJoin": "miter",
            "strokeMiterLimit": 4,
            "scaleX": 1,
            "scaleY": 1,
            "angle": 0,
            "flipX": false,
            "flipY": false,
            "opacity": 1,
            "shadow": null,
            "visible": true,
            "clipTo": null,
            "backgroundColor": "",
            "fillRule": "nonzero",
            "paintFirst": "fill",
            "globalCompositeOperation": "source-over",
            "transformMatrix": null,
            "skewX": 0,
            "skewY": 0,
            "radius": 102,
            "startAngle": 0,
            "endAngle": 6.283185307179586
        },
        {
            "type": "ellipse",
            "version": "2.4.6",
            "originX": "left",
            "originY": "top",
            "left": 492,
            "top": 614,
            "width": 204,
            "height": 76,
            "fill": "transparent",
            "stroke": "black",
            "strokeWidth": 3,
            "strokeDashArray": null,
            "strokeLineCap": "butt",
            "strokeDashOffset": 0,
            "strokeLineJoin": "miter",
            "strokeMiterLimit": 4,
            "scaleX": 1,
            "scaleY": 1,
            "angle": 0,
            "flipX": false,
            "flipY": false,
            "opacity": 1,
            "shadow": null,
            "visible": true,
            "clipTo": null,
            "backgroundColor": "",
            "fillRule": "nonzero",
            "paintFirst": "fill",
            "globalCompositeOperation": "source-over",
            "transformMatrix": null,
            "skewX": 0,
            "skewY": 0,
            "rx": 102,
            "ry": 38
        },
        {
            "type": "rect",
            "version": "2.4.6",
            "originX": "left",
            "originY": "top",
            "left": 432,
            "top": 799,
            "width": 283,
            "height": 70,
            "fill": "transparent",
            "stroke": "black",
            "strokeWidth": 3,
            "strokeDashArray": null,
            "strokeLineCap": "butt",
            "strokeDashOffset": 0,
            "strokeLineJoin": "miter",
            "strokeMiterLimit": 4,
            "scaleX": 1,
            "scaleY": 1,
            "angle": 0,
            "flipX": false,
            "flipY": false,
            "opacity": 1,
            "shadow": null,
            "visible": true,
            "clipTo": null,
            "backgroundColor": "",
            "fillRule": "nonzero",
            "paintFirst": "fill",
            "globalCompositeOperation": "source-over",
            "transformMatrix": null,
            "skewX": 0,
            "skewY": 0,
            "rx": 0,
            "ry": 0
        },
        {
            "type": "triangle",
            "version": "2.4.6",
            "originX": "left",
            "originY": "top",
            "left": 489,
            "top": 989,
            "width": 302,
            "height": 74,
            "fill": "transparent",
            "stroke": "black",
            "strokeWidth": 3,
            "strokeDashArray": null,
            "strokeLineCap": "butt",
            "strokeDashOffset": 0,
            "strokeLineJoin": "miter",
            "strokeMiterLimit": 4,
            "scaleX": 1,
            "scaleY": 1,
            "angle": 0,
            "flipX": false,
            "flipY": false,
            "opacity": 1,
            "shadow": null,
            "visible": true,
            "clipTo": null,
            "backgroundColor": "",
            "fillRule": "nonzero",
            "paintFirst": "fill",
            "globalCompositeOperation": "source-over",
            "transformMatrix": null,
            "skewX": 0,
            "skewY": 0
        },
        {
            "type": "lineArrow",
            "version": "2.4.6",
            "originX": "center",
            "originY": "center",
            "left": 599.5,
            "top": 1161.5,
            "width": 229,
            "height": 57,
            "fill": "transparent",
            "stroke": "black",
            "strokeWidth": 3,
            "strokeDashArray": null,
            "strokeLineCap": "butt",
            "strokeDashOffset": 0,
            "strokeLineJoin": "miter",
            "strokeMiterLimit": 4,
            "scaleX": 1,
            "scaleY": 1,
            "angle": 0,
            "flipX": false,
            "flipY": false,
            "opacity": 1,
            "shadow": null,
            "visible": true,
            "clipTo": null,
            "backgroundColor": "",
            "fillRule": "nonzero",
            "paintFirst": "fill",
            "globalCompositeOperation": "source-over",
            "transformMatrix": null,
            "skewX": 0,
            "skewY": 0,
            "x1": -114.5,
            "x2": 114.5,
            "y1": 28.5,
            "y2": -28.5
        }
    ],
    "width": 1440,
    "height": 1440
}