services:
  # fastapi:
  #   build:
  #     context: ..
  #     dockerfile: agilelink-ci/Dockerfile.fastapi
  #   volumes:
  #     - ../fastapi:/app
  #   ports:
  #     - "8000:8000"
  #   networks:
  #     - app-network
  notion-registration:
    container_name: notion_registration  # Custom container name
    hostname: notion_registration.local            # Custom hostname (domain name)
    build:
      context: ..
      dockerfile: agilelink-ci/Dockerfile.application.notionregistration
    ports:
      - "4011:4011"
    environment:
      - PORT=4011  # Sets the PORT environment variable inside the container
      - NOTION_OAuth_Client_Secret=${NOTION_OAuth_Client_Secret}
      - NOTION_OAuthClient_ID=${NOTION_OAuthClient_ID}
      - NOTION_OAuth_Reidrect_Uri=http://localhost:4011/callback
      - SESSION_Secret_Key=${SESSION_Secret_Key}
      - App_AlPortalBaseUrl=http://localhost:4011
      - App_FlashcardBaseUrl=http://localhost:4012
      - App_WhiteBoardBaseUrl=https://agilel.ink.local
    networks:
      - app-network
  flashcard:
    container_name: flashcard  # Custom container name
    hostname: flashcard.local            # Custom hostname (domain name)
    build:
      context: ..
      dockerfile: agilelink-ci/Dockerfile.application.flashcard
    ports:
      - "4012:4012"
    environment:
      - PORT=4012
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_ORGANIZATION_ID=${OPENAI_ORGANIZATION_ID}
      - OPENAI_PROJECT_ID=${OPENAI_PROJECT_ID}
      - OPENAI_MODEL_NAME=${OPENAI_MODEL_NAME}
      - Storage_AlPortalBaseUrl=http://notion_registration:4011
    networks:
      - app-network
  peer2peer:
    build:
      context: ..
      dockerfile: agilelink-ci/Dockerfile.peer2peer
    ports:
      - "4014:4014"
    environment:
      - PORT=4014
    networks:
      - app-network
  # nginx:
  #   build:
  #     context: ..
  #     dockerfile: agilelink-ci/Dockerfile.nginx
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - notion-registration
  #     - flashcard
  #   environment:
  #     - NOTION_REGISTRATION_URL=http://notion_registration:4011
  #     - FLASHCARD_URL=http://flashcard:4012
  #   networks:
  #     - app-network
  whiteboard:
    build:
      context: ..
      dockerfile: agilelink-ci/Dockerfile.application.whiteboard
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network
    extra_hosts:
      - "agilel.ink.local:127.0.0.1"

networks:
  app-network:
    driver: bridge
