services:
  # fastapi:
  #   build:
  #     context: ..
  #     dockerfile: agilelink-ci/Dockerfile.fastapi
  #   volumes:
  #     - ../fastapi:/app
  #   ports:
  #     - "8000:8000"
  #   networks:
  #     - app-network
  notion-registration:
    container_name: notion_registration  # Custom container name
    hostname: notion_registration.local            # Custom hostname (domain name)
    build:
      context: ..
      dockerfile: agilelink-ci/Dockerfile.application.notionregistration
    ports:
      - "4011:4011"
    environment:
      - PORT=4011  # Sets the PORT environment variable inside the container
      - NOTION_OAuth_Client_Secret=${NOTION_OAuth_Client_Secret}
      - NOTION_OAuthClient_ID=${NOTION_OAuthClient_ID}
      - NOTION_OAuth_Reidrect_Uri=http://localhost:4011/callback
      - SESSION_Secret_Key=${SESSION_Secret_Key}
    networks:
      - app-network
  flashcard:
    container_name: flashcard  # Custom container name
    hostname: flashcard.local            # Custom hostname (domain name)
    build:
      context: ..
      dockerfile: agilelink-ci/Dockerfile.application.flashcard
    ports:
      - "4012:4012"
    environment:
      - PORT=4012
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_ORGANIZATION_ID=${OPENAI_ORGANIZATION_ID}
      - OPENAI_PROJECT_ID=${OPENAI_PROJECT_ID}
      - OPENAI_MODEL_NAME=${OPENAI_MODEL_NAME}
      - Storage_AlPortalBaseUrl=http://notion_registration:4011
    networks:
      - app-network
  # angular:
  #   build:
  #     context: ..
  #     dockerfile: agilelink-ci/Dockerfile.angular
  #   ports:
  #     - "81:3000"  # Maps port 81 on the host to port 3000 in the container
  #   environment:
  #     - PORT=3000  # Sets the PORT environment variable inside the container
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge
