services:
  fastapi:
    build:
      context: ..
      dockerfile: agilelink-ci/Dockerfile.fastapi
    volumes:
      - ../fastapi:/app
    ports:
      - "8000:8000"
    networks:
      - app-network

  angular:
    build:
      context: ..
      dockerfile: agilelink-ci/Dockerfile.angular
    ports:
      - "81:3000"  # Maps port 81 on the host to port 3000 in the container
    environment:
      - PORT=3000  # Sets the PORT environment variable inside the container
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
