# Dockerfile.angular
FROM node:18 AS build

WORKDIR /app

COPY ./reactive-UI/package.json .
COPY ./reactive-UI/package-lock.json .

RUN npm install

COPY ./reactive-UI/ .

RUN npm run build --omit=dev

EXPOSE 3000

CMD ["node", "dist/reactive-ui/server/server.mjs"]
