name: Cypress Tests

on:
  push:
    branches:
      - master  # Only trigger on push to master
  pull_request:
    branches:  # Trigger on pull requests to any branch
      - '**'  # Matches any branch

jobs:
  cypress-test:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        shell: cmd
        run: |
          cd e2e
          npm install

      - name: Run Cypress tests
        shell: cmd
        run: |
          cd e2e
          npm start
